extends RefCounted

const NAME_ROWS: Array[Dictionary] = [
	{"id": &"fighter", "names": ["Aldric", "Branna", "Cedric", "Dagna", "Garrick", "Hilda", "Rowan", "Thane"], "capabilities": [&"area", &"melee", &"physical"]},
	{"id": &"ranger", "names": ["Ash", "Briar", "Elowen", "Fen", "Linden", "Robin", "Sylvi", "Wren"], "capabilities": [&"physical", &"projectile", &"ranged"]},
	{"id": &"mage", "names": ["Alaric", "Circe", "Elara", "Isolde", "Lucan", "Mira", "Orin", "Selene"], "capabilities": [&"area", &"fire", &"projectile"]},
	{"id": &"cleric", "names": ["Ansel", "Beatrix", "Clement", "Faith", "Mercy", "Sabine", "Tobias", "Verity"], "capabilities": [&"healing", &"lightning", &"projectile"]},
	{"id": &"paladin", "names": ["Aegis", "Armand", "Galahad", "Helena", "Roland", "Seraphine", "Tristan", "Valora"], "capabilities": [&"area", &"block", &"melee", &"physical", &"regeneration"]},
	{"id": &"rogue", "names": ["Corvin", "Flick", "Jax", "Nyx", "Rook", "Shade", "Talia", "Vesper"], "capabilities": [&"area", &"crit", &"dodge", &"life_steal", &"melee", &"physical"]},
	{"id": &"frost_mage", "names": ["Boreas", "Eira", "Iskra", "Lumi", "Neve", "Rime", "Skadi", "Ylva"], "capabilities": [&"area", &"cold", &"projectile"]},
	{"id": &"warlock", "names": ["Azrael", "Belladonna", "Dorian", "Hex", "Lilith", "Malachar", "Morwen", "Sable"], "capabilities": [&"chaos", &"life_steal", &"projectile", &"ranged"]},
	{"id": &"marksman", "names": ["Arlen", "Blythe", "Cora", "Fletcher", "Hawke", "Ivo", "Petra", "Quinn"], "capabilities": [&"bow", &"crit", &"physical", &"projectile", &"ranged"]},
	{"id": &"generic", "names": ["Ada", "Bram", "Celine", "Dax", "Erin", "Finn", "Gia", "Hugo", "Iris", "Joren", "Kara", "Leon"]},
]

static var CARD_ROWS: Array[Dictionary] = [
	{"id": &"hold_the_line", "name": "Hold the Line", "summary": "Stand firm with greater health and armor.", "scope": UpgradeDefinition.Scope.CLASS_SPECIFIC, "classes": [&"fighter"], "max": 1, "effects": [_effect(&"max_health", StatModifier.Operation.INCREASED, 0.20), _effect(&"armor", StatModifier.Operation.FLAT, 5.0)]},
	{"id": &"quickdraw", "name": "Quickdraw", "summary": "Loose faster arrows with greater projectile velocity.", "scope": UpgradeDefinition.Scope.CLASS_SPECIFIC, "classes": [&"ranger"], "max": 1, "effects": [_effect(&"attack_speed", StatModifier.Operation.INCREASED, 0.20), _effect(&"projectile_speed", StatModifier.Operation.INCREASED, 0.25)]},
	{"id": &"living_flame", "name": "Living Flame", "summary": "Intensify fire magic and expanding blasts.", "scope": UpgradeDefinition.Scope.CLASS_SPECIFIC, "classes": [&"mage"], "max": 1, "effects": [_effect(&"fire_damage", StatModifier.Operation.INCREASED, 0.25), _effect(&"area_size", StatModifier.Operation.INCREASED, 0.20)]},
	{"id": &"sacred_conduit", "name": "Sacred Conduit", "summary": "Channel stronger healing and lightning.", "scope": UpgradeDefinition.Scope.CLASS_SPECIFIC, "classes": [&"cleric"], "max": 1, "effects": [_effect(&"healing_power", StatModifier.Operation.INCREASED, 0.25), _effect(&"lightning_damage", StatModifier.Operation.INCREASED, 0.25)]},
	{"id": &"consecrated_bulwark", "name": "Consecrated Bulwark", "summary": "Block more attacks and recover health steadily.", "scope": UpgradeDefinition.Scope.CLASS_SPECIFIC, "classes": [&"paladin"], "max": 1, "effects": [_effect(&"block_chance", StatModifier.Operation.FLAT, 0.10), _effect(&"health_regeneration", StatModifier.Operation.FLAT, 1.5)]},
	{"id": &"cutthroat_instinct", "name": "Cutthroat Instinct", "summary": "Strike critically and steal life from wounded foes.", "scope": UpgradeDefinition.Scope.CLASS_SPECIFIC, "classes": [&"rogue"], "max": 1, "effects": [_effect(&"crit_chance", StatModifier.Operation.FLAT, 0.10), _effect(&"crit_multiplier", StatModifier.Operation.FLAT, 0.25), _effect(&"life_steal", StatModifier.Operation.FLAT, 0.05)]},
	{"id": &"heart_of_winter", "name": "Heart of Winter", "summary": "Deepen cold magic and widen frozen bursts.", "scope": UpgradeDefinition.Scope.CLASS_SPECIFIC, "classes": [&"frost_mage"], "max": 1, "effects": [_effect(&"cold_damage", StatModifier.Operation.INCREASED, 0.25), _effect(&"area_size", StatModifier.Operation.INCREASED, 0.20)]},
	{"id": &"blood_covenant", "name": "Blood Covenant", "summary": "Trade vitality for chaos power and life steal.", "scope": UpgradeDefinition.Scope.CLASS_SPECIFIC, "classes": [&"warlock"], "max": 1, "effects": [_effect(&"chaos_damage", StatModifier.Operation.INCREASED, 0.30), _effect(&"life_steal", StatModifier.Operation.FLAT, 0.08), _effect(&"max_health", StatModifier.Operation.REDUCED, 0.15)]},
	{"id": &"deadeye", "name": "Deadeye", "summary": "Trade attack speed for devastating long-range physical shots.", "scope": UpgradeDefinition.Scope.CLASS_SPECIFIC, "classes": [&"marksman"], "max": 1, "effects": [_effect(&"physical_damage", StatModifier.Operation.MORE, 0.30), _effect(&"attack_range", StatModifier.Operation.INCREASED, 0.20), _effect(&"crit_multiplier", StatModifier.Operation.FLAT, 0.25), _effect(&"attack_speed", StatModifier.Operation.LESS, 0.15)]},
	{"id": &"martial_training", "name": "Martial Training", "summary": "Reinforce martial offense and armor.", "scope": UpgradeDefinition.Scope.CHARACTER, "all": [&"martial"], "max": 3, "effects": [_effect(&"physical_damage", StatModifier.Operation.INCREASED, 0.08), _effect(&"armor", StatModifier.Operation.FLAT, 1.0)]},
	{"id": &"ranged_calibration", "name": "Ranged Calibration", "summary": "Extend range and accelerate projectiles.", "scope": UpgradeDefinition.Scope.CHARACTER, "all": [&"ranged"], "max": 3, "effects": [_effect(&"attack_range", StatModifier.Operation.INCREASED, 0.10), _effect(&"projectile_speed", StatModifier.Operation.INCREASED, 0.10)]},
	{"id": &"caster_discipline", "name": "Caster Discipline", "summary": "Cast harder and faster.", "scope": UpgradeDefinition.Scope.CHARACTER, "all": [&"caster"], "max": 3, "effects": [_effect(&"damage", StatModifier.Operation.INCREASED, 0.08), _effect(&"attack_speed", StatModifier.Operation.INCREASED, 0.08)]},
	{"id": &"skirmishers_rhythm", "name": "Skirmisher's Rhythm", "summary": "Evade attacks while moving more quickly.", "scope": UpgradeDefinition.Scope.CHARACTER, "all": [&"skirmisher"], "max": 3, "effects": [_effect(&"dodge_chance", StatModifier.Operation.FLAT, 0.04), _effect(&"move_speed", StatModifier.Operation.INCREASED, 0.05)]},
	{"id": &"projectile_mastery", "name": "Projectile Mastery", "summary": "Empower projectiles and the attacks that launch them.", "scope": UpgradeDefinition.Scope.CHARACTER, "all": [&"projectile"], "max": 3, "effects": [_effect(&"projectile_speed", StatModifier.Operation.INCREASED, 0.12), _effect(&"damage", StatModifier.Operation.INCREASED, 0.08, [], [&"projectile"])]},
	{"id": &"expanding_power", "name": "Expanding Power", "summary": "Enlarge area effects and their damage.", "scope": UpgradeDefinition.Scope.CHARACTER, "all": [&"area"], "max": 3, "effects": [_effect(&"area_size", StatModifier.Operation.INCREASED, 0.10), _effect(&"damage", StatModifier.Operation.INCREASED, 0.08, [], [&"area"])]},
	{"id": &"elemental_attunement", "name": "Elemental Attunement", "summary": "Strengthen every element the character can wield.", "scope": UpgradeDefinition.Scope.CHARACTER, "any": [&"fire", &"cold", &"lightning", &"chaos"], "max": 3, "effects": [_effect(&"fire_damage", StatModifier.Operation.INCREASED, 0.12, [&"fire"]), _effect(&"cold_damage", StatModifier.Operation.INCREASED, 0.12, [&"cold"]), _effect(&"lightning_damage", StatModifier.Operation.INCREASED, 0.12, [&"lightning"]), _effect(&"chaos_damage", StatModifier.Operation.INCREASED, 0.12, [&"chaos"])]},
	{"id": &"vanguard_wall", "name": "Vanguard Wall", "summary": "Fortify every Vanguard, including later recruits.", "scope": UpgradeDefinition.Scope.TRAIT, "all": [&"vanguard"], "max": 1, "effects": [_effect(&"armor", StatModifier.Operation.FLAT, 3.0), _effect(&"max_health", StatModifier.Operation.INCREASED, 0.10)]},
	{"id": &"arcane_convergence", "name": "Arcane Convergence", "summary": "Expand and empower every Arcane member's elements, including later recruits.", "scope": UpgradeDefinition.Scope.TRAIT, "all": [&"arcane"], "max": 1, "effects": [_effect(&"area_size", StatModifier.Operation.INCREASED, 0.12), _effect(&"fire_damage", StatModifier.Operation.INCREASED, 0.10, [&"fire"]), _effect(&"cold_damage", StatModifier.Operation.INCREASED, 0.10, [&"cold"]), _effect(&"lightning_damage", StatModifier.Operation.INCREASED, 0.10, [&"lightning"]), _effect(&"chaos_damage", StatModifier.Operation.INCREASED, 0.10, [&"chaos"])]},
	{"id": &"divine_covenant", "name": "Divine Covenant", "summary": "Improve healing and regeneration for every Divine member, including later recruits.", "scope": UpgradeDefinition.Scope.TRAIT, "all": [&"divine"], "max": 1, "effects": [_effect(&"healing_power", StatModifier.Operation.INCREASED, 0.15), _effect(&"health_regeneration", StatModifier.Operation.FLAT, 1.0)]},
	{"id": &"vitality", "name": "Vitality", "summary": "Build greater maximum health.", "scope": UpgradeDefinition.Scope.CHARACTER, "max": 5, "effects": [_effect(&"max_health", StatModifier.Operation.INCREASED, 0.08)]},
	{"id": &"tempered_armor", "name": "Tempered Armor", "summary": "Add reliable armor.", "scope": UpgradeDefinition.Scope.CHARACTER, "max": 5, "effects": [_effect(&"armor", StatModifier.Operation.FLAT, 2.0)]},
	{"id": &"ferocity", "name": "Ferocity", "summary": "Deal greater damage.", "scope": UpgradeDefinition.Scope.CHARACTER, "max": 5, "effects": [_effect(&"damage", StatModifier.Operation.INCREASED, 0.08)]},
	{"id": &"alacrity", "name": "Alacrity", "summary": "Attack more quickly.", "scope": UpgradeDefinition.Scope.CHARACTER, "max": 5, "effects": [_effect(&"attack_speed", StatModifier.Operation.INCREASED, 0.06)]},
	{"id": &"fleetfoot", "name": "Fleetfoot", "summary": "Move more quickly.", "scope": UpgradeDefinition.Scope.CHARACTER, "max": 5, "effects": [_effect(&"move_speed", StatModifier.Operation.INCREASED, 0.05)]},
	{"id": &"precision", "name": "Precision", "summary": "Gain critical strike chance.", "scope": UpgradeDefinition.Scope.CHARACTER, "max": 5, "effects": [_effect(&"crit_chance", StatModifier.Operation.FLAT, 0.03)]},
]

static var KEYWORD_ROWS: Array[Dictionary] = [
	_keyword(&"max_health", "Maximum Health", "The total damage a character can take before being downed."),
	_keyword(&"strength", "Strength", "A core attribute associated with physical power and forceful actions."),
	_keyword(&"dexterity", "Dexterity", "A core attribute associated with precision, agility, and quick actions."),
	_keyword(&"constitution", "Constitution", "A core attribute associated with toughness, endurance, and survival."),
	_keyword(&"intelligence", "Intelligence", "A core attribute associated with learned magic, analysis, and complex effects."),
	_keyword(&"wisdom", "Wisdom", "A core attribute associated with awareness, discipline, and restorative power."),
	_keyword(&"charisma", "Charisma", "A core attribute associated with presence, conviction, and influence."),
	_keyword(&"armor", "Armor", "Reduces incoming physical damage."),
	_keyword(&"move_speed", "Move Speed", "Controls how quickly a character moves."),
	_keyword(&"damage", "Damage", "Modifies all damage dealt by the character."),
	_keyword(&"attack_speed", "Attack Speed", "Controls how quickly attacks can be used."),
	_keyword(&"crit_chance", "Critical Strike Chance", "Each full 100% Critical Strike Chance guarantees another critical damage instance, and the remaining chance is rolled independently."),
	_keyword(&"multi_crit", "Multi-Crit", "Critical Strike Chance above 100% can produce multiple critical damage instances."),
	_keyword(&"crit_multiplier", "Critical Strike Multiplier", "The damage multiplier applied by a critical strike."),
	_keyword(&"attack_range", "Attack Range", "The maximum distance at which an attack can target."),
	_keyword(&"projectile_speed", "Projectile Speed", "Controls how quickly projectiles travel."),
	_keyword(&"area_size", "Area Size", "Scales the radius of area effects."),
	_keyword(&"cooldown_rate", "Cooldown Rate", "Controls how quickly ability cooldowns recover."),
	_keyword(&"healing_power", "Healing Power", "Modifies healing performed by the character."),
	_keyword(&"dodge_chance", "Dodge Chance", "The chance to avoid an incoming attack."),
	_keyword(&"block_chance", "Block Chance", "The chance to block an incoming hit."),
	_keyword(&"block_effectiveness", "Block Effectiveness", "Controls how much damage a successful block prevents."),
	_keyword(&"health_regeneration", "Health Regeneration", "Restores health steadily over time."),
	_keyword(&"life_steal", "Life Steal", "Restores health from damage dealt."),
	_keyword(&"pickup_radius", "Pickup Radius", "Controls how far away experience pickups can be collected."),
	_keyword(&"physical_damage", "Physical Damage", "Physical damage is mitigated by armor."),
	_keyword(&"fire_damage", "Fire Damage", "Modifies fire damage dealt by the character."),
	_keyword(&"cold_damage", "Cold Damage", "Modifies cold damage dealt by the character."),
	_keyword(&"lightning_damage", "Lightning Damage", "Modifies lightning damage dealt by the character."),
	_keyword(&"chaos_damage", "Chaos Damage", "Modifies chaos damage dealt by the character."),
	_keyword(&"fire_resistance", "Fire Resistance", "Reduces incoming fire damage."),
	_keyword(&"cold_resistance", "Cold Resistance", "Reduces incoming cold damage."),
	_keyword(&"lightning_resistance", "Lightning Resistance", "Reduces incoming lightning damage."),
	_keyword(&"chaos_resistance", "Chaos Resistance", "Reduces incoming chaos damage."),
	_keyword(&"melee_damage", "Melee Damage", "Modifies damage dealt by actions whose primary archetype is Melee."),
	_keyword(&"ranged_damage", "Ranged Damage", "Modifies damage dealt by actions whose primary archetype is Ranged."),
	_keyword(&"caster_damage", "Caster Damage", "Modifies damage dealt by actions whose primary archetype is Caster."),
	_keyword(&"party_influence", "Party Influence", "Measures the character's presence and influence within the party."),
	_keyword(&"physical", "Physical", "Describes attacks and characters that deal physical damage.", true),
	_keyword(&"fire", "Fire", "Describes attacks, characters, and traits aligned with fire.", true),
	_keyword(&"cold", "Cold", "Describes attacks, characters, and traits aligned with cold.", true),
	_keyword(&"lightning", "Lightning", "Describes attacks and characters aligned with lightning.", true),
	_keyword(&"chaos", "Chaos", "Describes attacks, characters, and traits aligned with chaos.", true),
	_keyword(&"area", "Area", "Describes effects that cover an area.", true),
	_keyword(&"melee", "Melee", "Describes attacks made at close range.", true),
	_keyword(&"projectile", "Projectile", "Describes attacks that launch a traveling projectile.", true),
	_keyword(&"ranged", "Ranged", "Describes characters and attacks built for distance.", true),
	_keyword(&"healing", "Healing", "Describes actions that restore health.", true),
	_keyword(&"block", "Block", "Describes characters capable of blocking attacks.", true),
	_keyword(&"regeneration", "Regeneration", "Describes characters capable of restoring health over time.", true),
	_keyword(&"crit", "Critical", "Describes characters specialized in critical strikes.", true),
	_keyword(&"dodge", "Dodge", "Describes characters capable of avoiding attacks.", true),
	_keyword(&"martial", "Martial", "A trait shared by weapon-trained characters.", true),
	_keyword(&"vanguard", "Vanguard", "A trait shared by durable frontline characters.", true),
	_keyword(&"arcane", "Arcane", "A trait shared by characters trained in area magic.", true),
	_keyword(&"caster", "Caster", "A trait shared by characters who rely on spells.", true),
	_keyword(&"divine", "Divine", "A trait shared by characters empowered by sacred magic.", true),
	_keyword(&"support", "Support", "A trait shared by characters who aid allies.", true),
	_keyword(&"skirmisher", "Skirmisher", "A trait shared by mobile evasive characters.", true),
	_keyword(&"occult", "Occult", "A trait shared by characters who wield forbidden power.", true),
	_keyword(&"bow", "Bow", "A trait shared by specialized bow users.", true),
	_keyword(&"armour_light", "Light Armour", "Allows light armour equipment.", true),
	_keyword(&"armour_medium", "Medium Armour", "Allows medium armour equipment.", true),
	_keyword(&"armour_heavy", "Heavy Armour", "Allows heavy armour equipment.", true),
	_keyword(&"one_hand_sword", "One-Handed Sword", "Allows one-handed sword equipment.", true),
	_keyword(&"shield", "Shield", "Allows shield equipment.", true),
	_keyword(&"one_hand_hammer", "One-Handed Hammer", "Allows one-handed hammer equipment.", true),
	_keyword(&"bow_light_medium", "Light and Medium Bow", "Allows light and medium bow equipment.", true),
	_keyword(&"greatbow", "Greatbow", "Allows greatbow equipment.", true),
	_keyword(&"dagger", "Dagger", "Allows dagger equipment.", true),
	_keyword(&"dual_wield", "Dual Wield", "Allows compatible weapons in both hands.", true),
	_keyword(&"caster_wand", "Caster Wand", "Allows arcane wand equipment.", true),
	_keyword(&"caster_focus", "Caster Focus", "Allows arcane focus equipment.", true),
	_keyword(&"caster_staff", "Caster Staff", "Allows two-handed caster staff equipment.", true),
	_keyword(&"divine_sceptre", "Divine Sceptre", "Allows divine sceptre equipment.", true),
	_keyword(&"divine_tome", "Divine Tome", "Allows divine tome equipment.", true),
	_keyword(&"occult_wand", "Occult Wand", "Allows occult wand equipment.", true),
	_keyword(&"occult_grimoire", "Occult Grimoire", "Allows occult grimoire equipment.", true),
	_keyword(&"increased", "Increased", "An additive modifier combined with other increased and reduced values."),
	_keyword(&"reduced", "Reduced", "An additive penalty combined with increased and reduced values."),
	_keyword(&"more", "More", "A multiplicative modifier applied after increased and reduced values."),
	_keyword(&"less", "Less", "A multiplicative penalty applied after increased and reduced values."),
]

static func _effect(stat_id: StringName, operation: int, value: float, capability_tags: Array = [], action_tags: Array = []) -> Dictionary:
	return {"stat": stat_id, "operation": operation, "value": value, "capabilities": capability_tags, "actions": action_tags}

static func _keyword(id: StringName, display_name: String, explanation: String, is_capability_tag := false) -> Dictionary:
	return {"id": id, "name": display_name, "explanation": explanation, "capability": is_capability_tag}
