extends RefCounted

const ATTACK_ROWS: Array[Dictionary] = [
	{"path": "res://data/attacks/paladin_smite.tres", "id": &"paladin_smite", "kind": AttackDefinition.Kind.MELEE_CLEAVE, "type": &"physical", "amount": 16.0, "power": 0.0, "cooldown": 1.05, "range": 2.1, "speed": 0.0, "area": 1.4, "tags": [&"area", &"melee", &"physical"], "crit": true},
	{"path": "res://data/attacks/rogue_flurry.tres", "id": &"rogue_flurry", "kind": AttackDefinition.Kind.MELEE_CLEAVE, "type": &"physical", "amount": 8.0, "power": 0.0, "cooldown": 0.32, "range": 2.0, "speed": 0.0, "area": 0.9, "tags": [&"area", &"melee", &"physical", &"skirmisher"], "crit": true},
	{"path": "res://data/attacks/frost_shard.tres", "id": &"frost_shard", "kind": AttackDefinition.Kind.AREA_PROJECTILE, "type": &"cold", "amount": 20.0, "power": 0.0, "cooldown": 1.35, "range": 12.5, "speed": 10.0, "area": 3.0, "tags": [&"area", &"caster", &"cold", &"projectile"], "crit": true},
	{"path": "res://data/attacks/warlock_bolt.tres", "id": &"warlock_bolt", "kind": AttackDefinition.Kind.PROJECTILE, "type": &"chaos", "amount": 30.0, "power": 0.0, "cooldown": 1.75, "range": 12.5, "speed": 9.0, "area": 0.0, "tags": [&"caster", &"chaos", &"projectile"], "crit": true},
	{"path": "res://data/attacks/marksman_heavy_shot.tres", "id": &"marksman_heavy_shot", "kind": AttackDefinition.Kind.PROJECTILE, "type": &"physical", "amount": 42.0, "power": 0.0, "cooldown": 2.2, "range": 16.0, "speed": 22.0, "area": 0.0, "tags": [&"bow", &"physical", &"projectile", &"ranged"], "crit": true},
]

const CLASS_ROWS: Array[Dictionary] = [
	{"path": "res://data/classes/paladin.tres", "id": &"paladin", "name": "Paladin", "role": ClassDefinition.Role.FRONTLINE, "color": Color("e6c85f"), "traits": [&"divine", &"vanguard", &"martial"], "tags": [&"area", &"block", &"melee", &"physical", &"regeneration", &"armour_heavy", &"one_hand_hammer", &"shield"], "health": 220.0, "armor": 18.0, "speed": 5.6, "preferred": 2.0, "engagement": 4.5, "tether": 8.5, "attack": &"paladin_smite", "overrides": {&"block_chance": 0.18, &"block_effectiveness": 0.55, &"health_regeneration": 1.5}},
	{"path": "res://data/classes/rogue.tres", "id": &"rogue", "name": "Rogue", "role": ClassDefinition.Role.MIDLINE, "color": Color("a95be8"), "traits": [&"martial", &"skirmisher"], "tags": [&"area", &"crit", &"dodge", &"life_steal", &"melee", &"physical", &"armour_light", &"dagger", &"dual_wield"], "health": 72.0, "armor": 0.0, "speed": 7.4, "preferred": 1.4, "engagement": 3.0, "tether": 8.0, "attack": &"rogue_flurry", "overrides": {&"crit_chance": 0.10, &"crit_multiplier": 1.75, &"dodge_chance": 0.18, &"life_steal": 0.05}},
	{"path": "res://data/classes/frost_mage.tres", "id": &"frost_mage", "name": "Frost Mage", "role": ClassDefinition.Role.BACKLINE, "color": Color("70c8ff"), "traits": [&"arcane", &"caster", &"cold"], "tags": [&"area", &"cold", &"projectile", &"armour_light", &"caster_staff"], "health": 78.0, "armor": 0.0, "speed": 6.0, "preferred": 6.5, "engagement": 12.5, "tether": 12.5, "attack": &"frost_shard", "overrides": {}},
	{"path": "res://data/classes/warlock.tres", "id": &"warlock", "name": "Warlock", "role": ClassDefinition.Role.BACKLINE, "color": Color("7e4bc4"), "traits": [&"occult", &"caster", &"chaos"], "tags": [&"chaos", &"life_steal", &"projectile", &"armour_light", &"occult_wand", &"occult_grimoire"], "health": 82.0, "armor": 1.0, "speed": 5.8, "preferred": 6.0, "engagement": 12.5, "tether": 12.5, "attack": &"warlock_bolt", "overrides": {&"crit_chance": 0.10, &"chaos_damage": 1.10, &"life_steal": 0.12}},
	{"path": "res://data/classes/marksman.tres", "id": &"marksman", "name": "Marksman", "role": ClassDefinition.Role.MIDLINE, "color": Color(0.27579924, 0.36415747, 0.056183092, 1.0), "traits": [&"martial", &"ranged", &"bow"], "tags": [&"bow", &"crit", &"physical", &"projectile", &"ranged", &"armour_light", &"armour_medium", &"bow_light_medium", &"greatbow"], "health": 80.0, "armor": 2.0, "speed": 5.8, "preferred": 8.0, "engagement": 16.0, "tether": 16.0, "attack": &"marksman_heavy_shot", "overrides": {&"crit_chance": 0.10, &"crit_multiplier": 2.0}},
]
